#!/usr/bin/env bash

## Author  : Aditya Shakya (adi1090x)
## Github  : @adi1090x
#
## Applets : Power Menu

# Import shared content
ROFI_DIR=$HOME/.dotfiles/config/rofi/menu/
theme="$ROFI_DIR/styles/text.rasi"
source $ROFI_DIR/shared/common.sh

# Layout
list_col='1'
list_row='3'

# Options
option_1="	Back"
option_2="	Brightness"
option_3="墳	Volume"

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3" | rofi_cmd
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $option_1)
		sleep 0.2
		$ROFI_DIR/launcher
        ;;
    $option_2)
		$ROFI_DIR/brightness
        ;;
    $option_3)
		pavucontrol &
        ;;
	*)
		exit
		;;
esac

