#!/bin/sh

# default params
time="now + 45 minutes"
message="Session Finished"

# flags
while getopts ":t:m:" OPTION; do
  case "$OPTION" in
    t)
	  time=${OPTARG}
      ;;
    m)
	  message=${OPTARG}
      ;;
    ?)
      echo "script usage: $(basename \$0) [-t] [-m]" >&2
      exit 1
      ;;
  esac
done
shift $((OPTIND-1))


# notification
at "$time" << ENDMARKER
	dunstify "Alarm: ${message}" 
ENDMARKER
