#!/bin/sh

# starts applets in correct order

nextcloud --background & # establish connection to cloud server
sleep 1

# signal-desktop --start-in-tray --no-sandbox & # secure messenger
# sleep 2
#
# nm-applet & # network control
# sleep 1
