#!/bin/sh

# NOTES:
# Changing Content	-> Overrides Cards
# Changing Title	-> Creates new Card

# TODO:
# 1. Get Current Path
# 2. Manipulate to know which subject
# 3. Evoke command on edit in vim
# 4. Fallback -> Select Menu

subject=$1

DIRS="lectures apkg --sync --delete"
ARGS="--sync --delete --prefix"
SEMESTER="23SP"
HOMEDIR=$HOME/nextcloud/mcs/$SEMESTER
DOCSDIR=$HOMEDIR/docs/$subject/


sync() {
	cd $DOCSDIR
	mdankideck $DIRS $ARGS \"$subject::\"
}


# while true; do
# 	sync
# 	inotifywait \
# 		--event modify \
# 		--event create \
# 		--event delete \
# 		--timeout 300 \
# 		--recursive "$DOCSDIR"
# done

sync
