#!/usr/bin/env bash

# Read the first argument
ARG=$1
BASEDIR=$HOME/nextcloud/todo

CATEGORY=$(basename $(pwd))
DIR="$BASEDIR/$CATEGORY"

create_file() {
	# generate id and file
	UUID=$(uuidgen)
	ID=$(echo "_$UUID" | cut -c1-6)
	FILE="$DIR/$ID.md"

	# select to clipboard
	echo -n "$ID.md" | xclip -sel clipboard

	# create file only if it does not exist
	if [ -f "$FILE" ]; then
	  echo "Error: File already exists"
	  exit 1
	else
	  touch "$FILE"
	fi
}

if [ "$CATEGORY" != "dev" ] && [ "$CATEGORY" != "pers" ] && [ "$CATEGORY" != "uni" ]; then
  echo "Error: Variable must be either dev, pers, or uni"
  exit 1
fi

create_file
