#!/usr/bin/env bash

# Import shared content
ROFI_DIR=$HOME/.dotfiles/config/rofi/menu/
theme="$ROFI_DIR/styles/icon.rasi"
source $ROFI_DIR/shared/common.sh

list_col='7'
list_row='1'

option_1="爵"
option_2=""
option_3=""
option_4=""
option_5=""
option_6=""

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6" | rofi_cmd
}

# Actions
chosen="$(run_rofi)"
sleep 0.2
case ${chosen} in
    $option_1)
		$ROFI_DIR/quicklinks
        ;;
    $option_2)
		$ROFI_DIR/powermenu
        ;;
    $option_3)
		$ROFI_DIR/apps
        ;;
    $option_4)
		blueberry &
        ;;
    $option_5)
		$ROFI_DIR/settings
        ;;
    $option_6)
		exit
        ;;
esac

