#!/usr/bin/env bash

# Import shared content
theme="./styles/icon.rasi"
source "./shared/common.sh"

list_col='7'
list_row='1'

option_1="爵"
option_2=""
option_3=""
option_4=""
option_5=""
option_6=""

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6" | rofi_cmd
}

# Actions
chosen="$(run_rofi)"
sleep 0.2
case ${chosen} in
    $option_1)
		./quicklinks
        ;;
    $option_2)
		./powermenu
        ;;
    $option_3)
		./apps
        ;;
    $option_4)
		blueberry &
        ;;
    $option_5)
		./settings
        ;;
    $option_6)
		exit
        ;;
esac

