#!/usr/bin/env bash

## Author  : Aditya Shakya (adi1090x)
## Github  : @adi1090x
#
## Applets : Power Menu

# Import shared content
theme="./styles/text.rasi"
source "./shared/common.sh"

# Layout
list_col='1'
list_row='5'

# Options
option_1="	Back"
option_2="	Lock"
option_3="	Suspend"
option_4="	Reboot"
option_5="	Shutdown"
yes=' Yes'
no=' No'

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5" | rofi_cmd
}

# Ask for confirmation
confirm_exit() {
	echo -e "$yes\n$no" | confirm_cmd
}

# Confirm and execute
confirm_run () {	
	sleep 0.2
	selected="$(confirm_exit)"
	if [[ "$selected" == "$yes" ]]; then
        ${1} && ${2} && ${3}
    else
		sleep 0.2
		./powermenu
    fi	
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $option_1)
		sleep 0.2
		./launcher
        ;;
    $option_2)
		slock &
        ;;
    $option_3)
		systemctl suspend &
        ;;
    $option_4)
		confirm_run 'systemctl reboot'
        ;;
    $option_5)
		confirm_run 'systemctl shutdown'
        ;;
	*)
		exit
		;;
esac

