#!/usr/bin/env bash

# Watch and sync Mail 
# Sync on changes and every minute
# Requires: inotify-tools

# Define the notify_on_failure function
function notify_on_failure() {
    "$@"
    exit_status=$?
    if [ $exit_status -ne 0 ]; then
        dunstify -u critical "Mail Command failed" "Exit status: $exit_status"
    fi
}

sync() {
    mbsync -a
}

if [[ -d ~/Mail/ ]]; then
    echo "Mail directory exists!" 
else
    echo "Error: Mail directory not found"
    exit
fi

while true; do
    if rbw unlocked; then
        notify_on_failure sync
        sync
        inotifywait \
            --event modify \
            --event create \
            --event delete \
            --timeout 60 \
            --recursive "$HOME/Mail/INBOX/"
    else
        echo "Vault is locked. Waiting for 60 seconds before checking again."
        sleep 60
    fi
done
