#!/usr/bin/env bash

# Watch vdirsyncer calendars.
# Sync on changes and every 5 minutes.
# Requires: inotify-tools

sync() {
	mbsync -a
}

if [[ -d ~/Mail/ ]]; then
	echo "Mail directory exists!" 
else
	echo "Error: Mail directory not found"
	exit
fi

while true; do
	sync
	inotifywait \
		--event modify \
		--event create \
		--event delete \
		--timeout 60 \
		--recursive "$HOME/Mail/INBOX/"
done

