#!/usr/bin/env bash

# Watch vdirsyncer calendars.
# Sync on changes and every 5 minutes.
# Requires: inotify-tools

sync() {
	vdirsyncer sync --force-delete
}

if [[ -d /data/nextcloud/.calendars ]]; then
	echo "Calendar directory exists!" 
else
	echo "Error: Calendar directory not found"
	exit
fi

while true; do
    if rbw unlocked; then
        sync
        inotifywait \
            --event modify \
            --event create \
            --event delete \
            --timeout 300 \
            --recursive "$HOME/nextcloud/.calendars/"
    else
        echo "Vault is locked. Waiting for 60 seconds before checking again."
        sleep 60
    fi
done

