#!/usr/bin/env bash

# requirments
# - download trayer from nixpkgs

# ideas
# - no border -> picom
# - bat indicator -> standard input (config?)

# toggle behavior
# - put into "invisible tag"
# - ability to toggle tag with mod + a

trayer \
--transparent true \
--expand true \
--widthtype request \
--alpha 255 \
--edge top \
--align right \
--width 50 \
--height 20 \
--monitor primary

# download stalonetray
# -> man stalonetray / github readme
