#!/bin/bash
set -e

DOTFILES_DIR="$HOME/.dotfiles"
SSH_DIR="$HOME/.ssh"
EMAIL="fabian.gubler@proton.me"
DISTRO=$(awk -F= '/^NAME/{print $2}' /etc/os-release)

# install ansible
if ! [ -x "$(command -v ansible)" ]; then
	if [  -n "$(uname -a | grep fedora)" ]; then
		sudo dnf install ansible -y
	else
		sudo apt install ansible -y
	fi
fi

# ssh
if ! [[ -f "$SSH_DIR/id_rsa" ]]; then
  mkdir -p "$SSH_DIR"

  chmod 700 "$SSH_DIR"

  ssh-keygen -b 4096 -t rsa -f "$SSH_DIR/id_rsa" -N "" -C "$USER@$HOSTNAME"

  cat "$SSH_DIR/id_rsa.pub" >> "$SSH_DIR/authorized_keys"

  chmod 600 "$SSH_DIR/authorized_keys"
fi

# change directory into the dotfiles folder
cd "$DOTFILES_DIR"

# run the playbook
ansible-playbook "$DOTFILES_DIR/main.yml" --ask-become-pass $@
